/* 
 * resch-config.h   Generic configuration of RESCH
 *
 * This file is automatically generated by configure script.
 */
#ifndef __RESCH_CONFIG_H__
#define __RESCH_CONFIG_H__

#define LINUX_KERNEL_MINOR_VERSION 3.16.0
#define NR_RT_CPUS 8
#define NR_RT_TASKS 64
#define NR_RT_COMPONENTS 8
#define NR_GPU_CARD_LIMIT 1
#define USE_NVIDIA_DRIVER
// #define USE_NOUVEAU_DRIVER
#define DEBUG_PRINT
#define USE_NVIDIA_DRIVER

#endif /* __RESCH_CONFIG_H__ */
