/* 
 * resch-config.h   Generic configuration of RESCH
 *
 * This file is automatically generated by configure script.
 */
#ifndef __RESCH_CONFIG_H__
#define __RESCH_CONFIG_H__

#define USE_YAKKETY 
#define LINUX_KERNEL_MINOR_VERSION 4.4.0-97-generic
#define NR_RT_CPUS 2
#define NR_RT_TASKS 64
#define NR_RT_COMPONENTS 8
#define NR_GPU_CARD_LIMIT 1
#define USE__DRIVER

#endif /* __RESCH_CONFIG_H__ */
