######################################################################
# Automatically generated by qmake (2.01a) ? 10? 23 08:29:28 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h mainwindow.h mysquare.h tracer.h
FORMS += mainwindow.ui
SOURCES += config.cpp main.cpp mainwindow.cpp mysquare.cpp tracer.cpp
