# Makefile
TARGET	= user_test
CC	= gcc

CFLAGS = -I/usr/local/cuda -I../../include
LIBS = -lpthread -lcuda -L/usr/lib/resch -lresch_gpu -lresch

# select GPU architecture
NV_ARCH = sm_35 

NVCC = /usr/local/cuda/bin/nvcc -arch $(NV_ARCH) -cubin
NV_SRC = loop

all:
	$(NVCC) -o $(NV_SRC)_gpu.cubin $(NV_SRC)_gpu.cu 
	gcc -o $(TARGET) $(CFLAGS) rt_task_gpu.c $(NV_SRC).c  $(LIBS)

clean:
	rm -f $(TARGET)*  ./*~ core* $(NV_SRC)_gpu.cubin
