######################################################################
# Automatically generated by qmake (2.01a) ? 10? 23 06:26:17 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += create_file.h mainwindow.h type.h
FORMS += mainwindow.ui
SOURCES += create_file.cpp main.cpp mainwindow.cpp
