#!/bin/sh

echo "-------- Set original file --------"

DISTRIBUTION="NULL"

if [ -e /opt/ros/indigo/lib/libroscpp.so ]; then
	DISTRIBUTION="indigo"
elif [ -e /opt/ros/jade/lib/libroscpp.so ]; then
	DISTRIBUTION="jade"
elif [ -e /opt/ros/kinetic/lib/libroscpp.so ]; then
	DISTRIBUTION="kinetic"
else
	echo "libroscpp.so does not found"
	echo "Stop uninstall script"
	exit 1
fi

echo "sudo cp /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup /opt/ros/${DISTRIBUTION}/lib/libroscpp.so"
sudo cp /opt/ros/${DISTRIBUTION}/lib/libroscpp.so.backup /opt/ros/${DISTRIBUTION}/lib/libroscpp.so
echo "sudo cp /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup /opt/ros/${DISTRIBUTION}/include/ros/ros.h"
sudo cp /opt/ros/${DISTRIBUTION}/include/ros/ros.h.backup /opt/ros/${DISTRIBUTION}/include/ros/ros.h
if [ -e /opt/ros/${DISTRIBUTION}/include/ros_rosch ]; then
	sudo rm -rf /opt/ros/${DISTRIBUTION}/include/ros_rosch
fi

echo "------------------------------------"
